function createfigure1(xdata1, ydata1, zdata1, X1, Z1)
%CREATEFIGURE1(XDATA1, YDATA1, ZDATA1, X1, Z1)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata
%  X1:  vector of x data
%  Z1:  vector of z data

%  Auto-generated by MATLAB on 11-Mar-2015 12:43:35

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
view(axes1,[-40.5 30]);
grid(axes1,'on');
hold(axes1,'all');

% Create surf
surf(xdata1,ydata1,zdata1,'Parent',axes1,'FaceLighting','phong',...
    'LineWidth',0.01,...
    'FaceColor','interp',...
    'EdgeAlpha',0.01);

% Create plot3
plot3(X1,ydata1,Z1,'MarkerSize',4,'Marker','o','LineWidth',3,...
    'LineStyle','none',...
    'Color',[1 1 1]);

% Create xlabel
xlabel('Left,Right: tau [ms]');

% Create ylabel
ylabel('time [s]');

% Create zlabel
zlabel('ICCF');

% Create title
title('[Left <->Right] (44.22-52.32), [T :0.50 ],Thriller Single Version .m4a');

