function createfigure(zdata1, cdata1)
%CREATEFIGURE(ZDATA1, CDATA1)
%  ZDATA1:  surface zdata
%  CDATA1:  surface cdata

%  Auto-generated by MATLAB on 06-Mar-2015 14:52:35

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
%view(axes1,[18.5 88]);
grid(axes1,'on');
hold(axes1,'all');

% Create surf
surf(zdata1,cdata1,'Parent',axes1,'LineStyle','none');

