close all
ui1=uicontrol('style','radiobutton','string','Push me!!!!! ','position',[20 20 80 20] ,'value',1,...
'callback',['if get(ui1,''value'') == get(ui2,''value''),set(ui2,''value'',0);end']);
ui2=uicontrol('style','radiobutton','string','Me too!!!!!','position',[120 20 80 20],...
'callback',['if get(ui1,''value'') == get(ui2,''value''),set(ui1,''value'',0);end']);
