close all
ui1=uicontrol('style','checkbox','string','Push me!','position',[20 20 80 20] ,'value',1,...
'callback',['fprintf(''[Push me][%d]\n'',get(ui1,''value''))']);ui2=uicontrol('style','checkbox','string','Me too!','position',[120 20 80 20],...
'callback',['fprintf(''[Me too][%d]\n'',get(ui2,''value''))']);
