plot(sin(1:100)); 
ui1=uicontrol('style','popupmenu','position',[40 20 100 20],... 
'string',[{'solid'},{'dotted'},{'dash-dot'},{'dashed'}],... 
'value',1,... 
'userdata',[{'-'};{':'};{'-.'};{'--'}],... 
'callback',['lineobj=findobj(''type'',''line'');',... 
'lineinfo=get(ui1,''userdata'');',... 
'set(lineobj,''linestyle'',lineinfo{get(ui1,''value'')})']);
