close all
ui1=uicontrol('style','radiobutton','string','Push me!!!!!','position',[20 20 80 20] ,'value',1,...
'callback',['set(ui1,''value'',1);set(ui2,''value'',0);']);
ui2=uicontrol('style','radiobutton','string','Me too!!!!!','position',[120 20 80 20],...
'callback',['set(ui1,''value'',0);set(ui2,''value'',1);']);
