ui1=uicontrol('style','text','string','Left text',...
'position',[20 20 80 20],'HorizontalAlignment','left');
ui2=uicontrol('style','text','string','Center text',...
'position',[120 20 80 20],'HorizontalAlignment','center');
ui3=uicontrol('style','text','string','Right text',...
'position',[220 20 80 20],'HorizontalAlignment','right');
