ui1=uicontrol('style','slider','units','pixcels','position',[40 20 100 20],...
              'Min',-180,'Max',180,'Value',-37.5,...
              'callback','AZ=get(ui1,''value'');EL=get(ui2,''value'');view(AZ,EL)');
ui2=uicontrol('style','slider','units','pixcels','position',[20 40 20 100],...
              'Min',-180,'Max',180,'Value',30,...
              'callback','AZ=get(ui1,''value'');EL=get(ui2,''value'');view(AZ,EL)');
